# Generated by Django 5.2.6 on 2025-09-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('app_name', models.CharField(default='maze_runner', max_length=255, verbose_name='App Name')),
                ('app_version', models.CharField(default='1.0.0', max_length=100, verbose_name='App Version')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Maintenance mode')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
    ]
