# Generated by Django 5.2.6 on 2025-09-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maze',
            name='growing_tree_algorithm_choice',
            field=models.CharField(choices=[('NEWEST', 'Newest'), ('RANDOM', 'Random'), ('HYBRID', 'Hybrid')], default='NEWEST'),
        ),
    ]
