# Generated by Django 5.2.6 on 2025-09-23 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0002_maze_growing_tree_algorithm_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='maze',
            name='hybrid_prob',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(1.0)], verbose_name='Hybrid Probability'),
        ),
    ]
