# Generated by Django 5.2.6 on 2025-09-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0003_maze_hybrid_prob'),
    ]

    operations = [
        migrations.AddField(
            model_name='maze',
            name='solved',
            field=models.BooleanField(default=False, verbose_name='Solved'),
        ),
        migrations.AddField(
            model_name='maze',
            name='solved_maze',
            field=models.BinaryField(blank=True, null=True, verbose_name='Solved Maze'),
        ),
    ]
