# Generated by Django 5.2.6 on 2025-09-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0004_maze_solved_maze_solved_maze'),
    ]

    operations = [
        migrations.AddField(
            model_name='maze',
            name='solved_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Solved Time'),
        ),
    ]
