# Generated by Django 5.2.6 on 2025-10-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0005_maze_solved_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='maze',
            name='maze_image',
            field=models.ImageField(blank=True, null=True, upload_to='mazes/', verbose_name='Maze Image'),
        ),
    ]
