# Generated by Django 5.2.6 on 2025-10-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0006_maze_maze_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='maze',
            name='solved_maze_image',
            field=models.ImageField(blank=True, null=True, upload_to='mazes/', verbose_name='Solved Maze Image'),
        ),
    ]
